### ISSUE TITLE
No sound output when using default Endpoint (ALSA)

### ISSUE THREAD

**Issue by Bobo1239** [tomaka/rodio#135]
So this is a bit strange: when running the cpal's ["beep" example](https://github.com/tomaka/cpal/blob/master/examples/beep.rs) (which uses `get_default_endpoint`) everything works as expected but running rodio's ["basic" example](https://github.com/tomaka/rodio/blob/master/examples/basic.rs) (which also uses the re-exported `get_default_endpoint`) no sound is playing.

Using the first endpoint from `get_endpoints_list` works as expected (in both examples).

I tried [changing the format selection](https://github.com/tomaka/rodio/blob/4ca81f7c5f51bfdda60029c87c8430361653be6b/src/engine.rs#L106) to use the first format like in the cpal example but that didn't help.

Apparently something's not right with the event loop because after I inserted a `println` [here](https://github.com/tomaka/rodio/blob/4ca81f7c5f51bfdda60029c87c8430361653be6b/src/engine.rs#L142) it's only printed exactly once.

edit: (In both examples the default endpoint is named "default" and the first endpoint from `get_endpoints_list` is "pulse".)

**Comment by Bobo1239** [comment]
Found something interesting: the cpal example also stops working working after one buffer was filled if the event loop is run on a separate thread (as rodio does it). (I also inserted a `thread::sleep` in the main thread so the program didn't just exit.)

**Comment by ivanovaleksey** [comment]
Hello, I have faced with the same issue.
There is no sound for any example.

**Comment by fschutt** [comment]
Yeah, can confirm. There's no sound for any of the examples.

**Comment by fschutt** [comment]
@tomaka @ivanovaleksey This issue disappears if you simply do a version bump (from 0.5.1 to the latest 0.5.2). However, now the sound plays very distorted (lots of stuttering between samples).

**Comment by tomaka** [comment]
Theoretically the formats supported by the machine (as reported by cpal) should be the formats supported directly by the hardware. This is not the case on ALSA because there is unfortunately no way to bypass their software layer, but is the case for other platforms.

Then rodio is supposed to automatically convert the samples rate of the source to the samples rate of the hardware.

Therefore the fix is not to choose the voice's samples rate based on the source. The current rate-choosing code is correct, and if the sound plays distorted then it indicates a bug in the conversion code.

**Comment by fschutt** [comment]
Well, with `cpal 5.0.1` there is no sound at all, so there's that.

With `cpal 6.0` I get sound, but it's distorted, only every second sample plays. So I'd definitely put this as a bug in the conversion code - what I don't get is why it doesn't happen on other operating systems.

**Comment by tomaka** [comment]
I can't reproduce on my Linux machine, however I noticed that when compiling in debug the decoding is not fast enough. Could you try compiling with `--release` to see if it works correctly for you?

**Comment by fschutt** [comment]
@tomaka It works now. It seems that the distorted sound I percieved was just the decoder not running fast enough. I did compile it on debug settings, my bad. And now the sound works, too (with the updated cpal version).

So for me, this issue is fixed. Not sure if other people can confirm this. I'll try again on a different computer, just to be sure.

**Comment by ivanovaleksey** [comment]
Hello, it works for me too even without `--release` compilation.
By the way now it compiles and works on mac OS!

**Comment by Bobo1239** [comment]
It doesn't work for me yet though I'm pretty sure it's a problem upstream so I'll close this issue and open a new one for cpal.
